Feature lifecycle
ROBOTIS-Platform/ros2_examples pull request #4
Opened 2019-09-30 09:01 UTC by routiful

Added lifecycle node and launch files

### Run examples_lifecycle
```bash
$ ros2 run examples_lifecycle robot
```

### Launch examples_lifecycle
```bash
$ ros2 launch examples_lifecycle bringup.launch.py auto_activate:=False
```

### Lifecycle client
```bash
$ ros2 lifecycle set /example/robot configure
$ ros2 lifecycle set /example/robot activate
$ ros2 lifecycle set /example/robot deactivate
$ ros2 lifecycle set /example/robot shutdown
```

2019-09-30 22:53 UTC, robotpilot commented
LGTM!
직접 테스트해봤는데 잘 동작하네요. (참고로 R2-D2의 멋진 친구의 정식 로봇명은 C-3PO입니다.)
노드를 직접 제어할 수 있어야 상태천이 및 미션 수행이 가능한데 아주 적절한 타이밍에 태훈씨가 예제를 만들어주었네요. 감사합니다.

2019-09-30 23:02 UTC, robotpilot approved these changes

2019-09-30 23:02 UTC, robotpilot commented on README.md
> +```
set 이외에도 `get`, `list` 등의 다른 명령어도 있지 않나요?

2019-09-30 23:02 UTC, robotpilot commented on examples_lifecycle/CMakeLists.txt
> +  "rclcpp"
순서 재배치 요망

2019-09-30 23:02 UTC, robotpilot commented on examples_lifecycle/include/examples_lifecycle/robot.hpp
> +#include <rclcpp_lifecycle/lifecycle_node.hpp>
헤더파일 순서 재배치 필요

2019-10-01 00:30 UTC, routiful commented
@kijongGil @EunSungYang @OhSungHyeon 
여러분 PR 좀 봐주세용~

2019-10-01 00:34 UTC, routiful commented on README.md
> +```
ReadMe에 `get`, `list`, `nodes` 명령어도 추가했습니당

2019-10-01 00:35 UTC, routiful commented on examples_lifecycle/CMakeLists.txt
> +  "rclcpp"
수정하였습니다

2019-10-01 00:35 UTC, routiful commented on examples_lifecycle/include/examples_lifecycle/robot.hpp
> +#include <rclcpp_lifecycle/lifecycle_node.hpp>
수정하였습니다

2019-10-01 02:32 UTC, movingChurch approved these changes

2019-10-01 02:40 UTC, kijongGil approved these changes
수고하셨습니다.

2019-10-01 02:40 UTC, kijongGil commented on examples_lifecycle/package.xml
> +    Examples of ROS 2 C++ nodes
@routiful  설명 예제에 맞게 수정 해야할꺼 같네요.

2019-10-01 02:53 UTC, routiful commented on examples_lifecycle/package.xml
> +    Examples of ROS 2 C++ nodes
살짝 수정했습니당

2019-10-01 08:47 UTC, routiful commented on examples_lifecycle/package.xml
> +    Examples of ROS 2 C++ nodes
@kijongGil PING~

2019-10-01 09:56 UTC, robotpilot commented
PING @OhSungHyeon

2019-10-04 07:15 UTC, OhSungHyeon commented
수고하셨습니다!

2019-10-04 07:28 UTC, OhSungHyeon requested changes

2019-10-04 07:28 UTC, OhSungHyeon commented on examples_lifecycle/src/main.cpp
> +void print_help()
헤더 파일과 본문 사이의 구분은 빈줄2개를 사용해야 합니다.

2019-10-04 07:28 UTC, OhSungHyeon commented on examples_lifecycle/src/robot.cpp
> +    if (!client_change_state_->wait_for_service(1s)) {
중괄호는 한줄을 점유해야합니다.

2019-10-04 07:36 UTC, routiful commented on examples_lifecycle/src/main.cpp
> +void print_help()
수정하였습니다.

2019-10-04 07:36 UTC, routiful commented on examples_lifecycle/src/robot.cpp
> +    if (!client_change_state_->wait_for_service(1s)) {
수정하였습니다.

2019-10-07 02:29 UTC, OhSungHyeon approved these changes

2019-10-07 02:42 UTC, merged